name: SpyInventories
version: 1.0.4
main: com.spygamingog.spyinventories.SpyInventories
api-version: '1.21'
author: SpyGamingOG
depend: [SpyCore]
description: Managed world group inventories for SpyCore networks.
